version: "3.7"

services:
    consul-server:
        image: docker.io/hashicorp/consul:1.15.4
        container_name: consul-server
        restart: always
        volumes:
            - ./config/server.json:/consul/config/server.json:ro
        ports:
            - "8500:8500"
            - "8600:8600/tcp"
            - "8600:8600/udp"
        network_mode: host
